// SPDX-License-Identifier: MIT
#include "canforge/text/Lexer.hpp"

#include <cctype>
#include <cstdlib>
#include <cstring>

namespace canforge::text {
namespace {

bool is_ident_start(char c) noexcept {
  const auto u = static_cast<unsigned char>(c);
  return std::isalpha(u) != 0 || c == '_' ||
         u >= 0x80;  // permit UTF-8 continuation bytes inside names
}

bool is_ident_continue(char c) noexcept {
  const auto u = static_cast<unsigned char>(c);
  return std::isalnum(u) != 0 || c == '_' || u >= 0x80;
}

bool is_digit(char c) noexcept {
  return c >= '0' && c <= '9';
}

std::size_t utf8_sequence_length(const unsigned char* p, std::size_t left) noexcept {
  const unsigned char c = p[0];
  if (c < 0x80u) {
    return 1;
  }
  std::size_t need = 0;
  if ((c & 0xE0u) == 0xC0u) {
    need = 2;
  } else if ((c & 0xF0u) == 0xE0u) {
    need = 3;
  } else if ((c & 0xF8u) == 0xF0u) {
    need = 4;
  } else {
    return 0;  // continuation byte or invalid lead
  }
  if (need > left) {
    return 0;
  }
  for (std::size_t i = 1; i < need; ++i) {
    if ((p[i] & 0xC0u) != 0x80u) {
      return 0;
    }
  }
  return need;
}

bool is_valid_utf8(const std::string& s) noexcept {
  const auto* p = reinterpret_cast<const unsigned char*>(s.data());  // NOLINT
  std::size_t i = 0;
  while (i < s.size()) {
    const std::size_t n = utf8_sequence_length(p + i, s.size() - i);
    if (n == 0) {
      return false;
    }
    i += n;
  }
  return true;
}

/// Latin-1 to UTF-8. Every byte 0x00..0xFF maps to exactly one code point, so
/// this never fails -- which is precisely why it is a safe fallback.
std::string latin1_to_utf8(const std::string& in) {
  std::string out;
  out.reserve(in.size() + in.size() / 4u);
  for (const char ch : in) {
    const auto c = static_cast<unsigned char>(ch);
    if (c < 0x80u) {
      out.push_back(static_cast<char>(c));
    } else {
      out.push_back(static_cast<char>(0xC0u | (c >> 6u)));
      out.push_back(static_cast<char>(0x80u | (c & 0x3Fu)));
    }
  }
  return out;
}

}  // namespace

const char* to_string(TokenKind k) noexcept {
  switch (k) {
    case TokenKind::End:        return "end of file";
    case TokenKind::Identifier: return "an identifier";
    case TokenKind::Integer:    return "an integer";
    case TokenKind::Real:       return "a number";
    case TokenKind::String:     return "a quoted string";
    case TokenKind::Colon:      return "':'";
    case TokenKind::Semicolon:  return "';'";
    case TokenKind::Comma:      return "','";
    case TokenKind::Pipe:       return "'|'";
    case TokenKind::At:         return "'@'";
    case TokenKind::Plus:       return "'+'";
    case TokenKind::Minus:      return "'-'";
    case TokenKind::LParen:     return "'('";
    case TokenKind::RParen:     return "')'";
    case TokenKind::LBracket:   return "'['";
    case TokenKind::RBracket:   return "']'";
    case TokenKind::Equals:     return "'='";
    case TokenKind::Dot:        return "'.'";
    case TokenKind::Slash:      return "'/'";
    case TokenKind::Unknown:    return "an unexpected character";
  }
  return "something";
}

Source Source::normalise(std::string bytes, std::string name) {
  Source s;
  s.name_ = std::move(name);

  // 1. UTF-8 byte order mark. Vector CANdb++ writes one; most other tools do
  //    not. Left in place it would become part of the first keyword.
  if (bytes.size() >= 3 && static_cast<unsigned char>(bytes[0]) == 0xEFu &&
      static_cast<unsigned char>(bytes[1]) == 0xBBu &&
      static_cast<unsigned char>(bytes[2]) == 0xBFu) {
    bytes.erase(0, 3);
    s.had_bom_ = true;
  }

  // 2. Encoding. DBC has no encoding declaration. Files written on Windows by
  //    older CANdb++ versions are Latin-1, so comments containing German
  //    umlauts are invalid UTF-8. Since Latin-1 decoding cannot fail, using it
  //    as the fallback means a mis-detected file still round-trips its bytes
  //    instead of losing them.
  if (!is_valid_utf8(bytes)) {
    bytes = latin1_to_utf8(bytes);
    s.had_latin1_ = true;
  }

  // 3. Line endings. CRLF is the norm; a stray lone CR appears in files that
  //    have been through a Mac-era editor.
  std::string out;
  out.reserve(bytes.size());
  for (std::size_t i = 0; i < bytes.size(); ++i) {
    if (bytes[i] == '\r') {
      s.had_crlf_ = true;
      if (i + 1 < bytes.size() && bytes[i + 1] == '\n') {
        ++i;
      }
      out.push_back('\n');
    } else {
      out.push_back(bytes[i]);
    }
  }

  // 4. Trailing newline. A file whose last line is `VAL_ ... ;` with no
  //    newline is common when a database has been generated by a script.
  if (!out.empty() && out.back() != '\n') {
    out.push_back('\n');
    s.had_no_final_newline_ = true;
  }

  s.text_ = std::move(out);
  s.line_starts_.push_back(0);
  for (std::size_t i = 0; i < s.text_.size(); ++i) {
    if (s.text_[i] == '\n' && i + 1 < s.text_.size()) {
      s.line_starts_.push_back(i + 1);
    }
  }
  return s;
}

std::string_view Source::line(std::uint32_t number) const {
  if (number == 0 || number > line_starts_.size()) {
    return {};
  }
  const std::size_t start = line_starts_[number - 1];
  const std::size_t end = text_.find('\n', start);
  return std::string_view{text_}.substr(
      start, (end == std::string::npos ? text_.size() : end) - start);
}

char Lexer::peek(std::size_t ahead) const noexcept {
  const std::size_t i = pos_ + ahead;
  return i < source_->text().size() ? source_->text()[i] : '\0';
}

bool Lexer::at_end() const noexcept { return pos_ >= source_->text().size(); }

char Lexer::advance() noexcept {
  const char c = source_->text()[pos_++];
  if (c == '\n') {
    ++line_;
    column_ = 1;
    at_line_start_ = true;
  } else {
    ++column_;
  }
  return c;
}

void Lexer::skip_trivia() noexcept {
  while (!at_end()) {
    const char c = peek();
    if (c == ' ' || c == '\t' || c == '\n' || c == '\v' || c == '\f') {
      advance();
      continue;
    }
    // Neither DBC nor the simulator config has a comment syntax in its
    // published form, but generators emit `//` headers and hand-written
    // configs want `#`. Both are skipped to end of line. Neither character
    // occurs in DBC outside a quoted string, which lex_string handles.
    if (c == '#') {
      while (!at_end() && peek() != '\n') {
        advance();
      }
      continue;
    }
    if (c == '/' && peek(1) == '/') {
      while (!at_end() && peek() != '\n') {
        advance();
      }
      continue;
    }
    return;
  }
}

void Lexer::error(core::ErrorCode code, SourceLocation where, std::string message,
                  std::string token) {
  Diagnostic d;
  d.severity = Severity::Error;
  d.code = code;
  d.where = where;
  d.message = std::move(message);
  d.token = std::move(token);
  d.source_line = std::string(source_->line(where.line));
  diagnostics_->add(std::move(d));
}

Token Lexer::lex_number() {
  const SourceLocation start = here();
  const std::size_t begin = pos_;
  bool is_real = false;

  while (is_digit(peek())) {
    advance();
  }
  if (peek() == '.' && is_digit(peek(1))) {
    is_real = true;
    advance();
    while (is_digit(peek())) {
      advance();
    }
  } else if (peek() == '.' && !is_ident_start(peek(1))) {
    // "3." occurs in hand-edited files.
    is_real = true;
    advance();
  }
  if ((peek() == 'e' || peek() == 'E')) {
    const bool signed_exponent = (peek(1) == '+' || peek(1) == '-');
    if ((signed_exponent && is_digit(peek(2))) || is_digit(peek(1))) {
      is_real = true;
      advance();  // e
      if (signed_exponent) {
        advance();
      }
      while (is_digit(peek())) {
        advance();
      }
    }
  }

  // A token like `3PMS` starts with a digit but is a node name, not a number.
  // Real databases contain such names, so instead of rejecting the file the
  // lexer reclassifies it as an identifier.
  if (is_ident_continue(peek()) && !is_real) {
    while (is_ident_continue(peek())) {
      advance();
    }
    Token t;
    t.kind = TokenKind::Identifier;
    t.text = std::string_view{source_->text()}.substr(begin, pos_ - begin);
    t.where = start;
    return t;
  }

  Token t;
  t.text = std::string_view{source_->text()}.substr(begin, pos_ - begin);
  t.where = start;
  const std::string literal(t.text);
  if (is_real) {
    t.kind = TokenKind::Real;
    t.real = std::strtod(literal.c_str(), nullptr);
  } else {
    t.kind = TokenKind::Integer;
    t.integer = std::strtoull(literal.c_str(), nullptr, 10);
    t.real = static_cast<double>(t.integer);
  }
  return t;
}

Token Lexer::lex_identifier() {
  const SourceLocation start = here();
  const std::size_t begin = pos_;
  while (is_ident_continue(peek())) {
    advance();
  }
  Token t;
  t.kind = TokenKind::Identifier;
  t.text = std::string_view{source_->text()}.substr(begin, pos_ - begin);
  t.where = start;
  return t;
}

Token Lexer::lex_string() {
  const SourceLocation start = here();
  const std::size_t begin = pos_;
  advance();  // opening quote

  std::string value;
  bool terminated = false;
  while (!at_end()) {
    const char c = peek();
    if (c == '\\') {
      // The published grammar has no escape sequence, but CANdb++ writes \"
      // for an embedded quote and \\ for a backslash, so both are honoured.
      // Any other backslash is kept verbatim, so Windows
      // paths inside comments survive.
      const char next = peek(1);
      if (next == '"' || next == '\\') {
        advance();
        value.push_back(advance());
        continue;
      }
      value.push_back(advance());
      continue;
    }
    if (c == '"') {
      // A doubled quote ("") is how some spreadsheet-derived exporters escape
      // a quote. Distinguishable from the end of the string by the next
      // character.
      if (peek(1) == '"') {
        advance();
        value.push_back(advance());
        continue;
      }
      advance();
      terminated = true;
      break;
    }
    // Newlines inside a string are legal: multi-line CM_ comments are common.
    value.push_back(advance());
  }

  Token t;
  t.kind = TokenKind::String;
  t.text = std::string_view{source_->text()}.substr(begin, pos_ - begin);
  t.where = start;
  t.value = std::move(value);
  if (!terminated) {
    error(core::ErrorCode::ParseUnterminatedString, start,
          "string literal is never closed", "\"");
  }
  return t;
}

std::vector<Token> Lexer::tokenise() {
  std::vector<Token> tokens;
  tokens.reserve(source_->text().size() / 6u + 16u);

  for (;;) {
    skip_trivia();
    const bool first = at_line_start_;
    at_line_start_ = false;
    if (at_end()) {
      Token end;
      end.kind = TokenKind::End;
      end.where = here();
      end.first_on_line = first;
      tokens.push_back(std::move(end));
      return tokens;
    }

    const char c = peek();
    Token t;
    if (is_digit(c) || (c == '.' && is_digit(peek(1)))) {
      t = lex_number();
    } else if (is_ident_start(c)) {
      t = lex_identifier();
    } else if (c == '"') {
      t = lex_string();
    } else {
      const SourceLocation start = here();
      const std::size_t begin = pos_;
      advance();
      TokenKind kind = TokenKind::Unknown;
      switch (c) {
        case ':': kind = TokenKind::Colon;    break;
        case ';': kind = TokenKind::Semicolon; break;
        case ',': kind = TokenKind::Comma;    break;
        case '|': kind = TokenKind::Pipe;     break;
        case '@': kind = TokenKind::At;       break;
        case '+': kind = TokenKind::Plus;     break;
        case '-': kind = TokenKind::Minus;    break;
        case '(': kind = TokenKind::LParen;   break;
        case ')': kind = TokenKind::RParen;   break;
        case '[': kind = TokenKind::LBracket; break;
        case ']': kind = TokenKind::RBracket; break;
        case '=': kind = TokenKind::Equals;   break;
        case '.': kind = TokenKind::Dot;      break;
        // A lone '/' is a path separator in a simulator config. Two of them
        // were already consumed as a comment by skip_trivia.
        case '/': kind = TokenKind::Slash;    break;
        default:  kind = TokenKind::Unknown;  break;
      }
      t.kind = kind;
      t.text = std::string_view{source_->text()}.substr(begin, pos_ - begin);
      t.where = start;
      if (kind == TokenKind::Unknown) {
        error(core::ErrorCode::ParseUnexpectedToken, start,
              "unexpected character in the input", std::string(t.text));
      }
    }
    t.first_on_line = first;
    tokens.push_back(std::move(t));
  }
}

}  // namespace canforge::text
